In [6]:
import numpy as np

print(np.__version__)


2.4.3


In [14]:
array = np.array([*range(0,20)])
print(array)
print(array * 2)  # doubles each element value

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [19]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])  # 2D array
 
print(array, array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] (4, 4)


In [34]:
print(array[::2])         # array[start:end:step]
print(array[::-1]) 

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(array[:, ::-1])   # gives all rows but only columns with index 0 & 1

print(array[::-1, ::-1])  # reverses all rows and columns

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
# given an array of Radius values.. return Area of circles for each radius

radius = [1,2,3]

print(array)
cicle_area = np.pi * np.array([*radius]) ** 2        # pi*r^2
print(cicle_area)

[1 2 3]
[ 3.14159265 12.56637061 28.27433388]
