In [6]:
import numpy as np

print(np.__version__)


2.4.3


In [14]:
array = np.array([*range(0,20)])
print(array)
print(array * 2)  # doubles each element value

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [19]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])  # 2D array
 
print(array, array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] (4, 4)


In [34]:
print(array[::2])         # array[start:end:step]
print(array[::-1]) 

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(array[:, ::-1])   # gives all rows but only columns with index 0 & 1

print(array[::-1, ::-1])  # reverses all rows and columns

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
# given an array of Radius values.. return Area of circles for each radius

radius = [1,2,3]

print(array)
cicle_area = np.pi * np.array([*radius]) ** 2        # pi*r^2
print(cicle_area)

[1 2 3]
[ 3.14159265 12.56637061 28.27433388]


In [47]:
scores = np.array([50,40,44,65,58,70,10,30])
print(scores)
low_scores = scores<30

print(low_scores)

scores[scores<30] = 0            # to all scores less than 30, assign the value 0
print(scores)





[50 40 44 65 58 70 10 30]
[False False False False False False  True False]
[50 40 44 65 58 70  0 30]


Broadcasting in numpy


In [48]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1)
print(array2)

print(array1 * array2)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [53]:
array = np.array([*range(1,11)])

print("Array : ", array)

print("\nSum : ", np.sum(array))
print("Average : ", np.average(array))
print("Mean : ", np.mean(array))
print("Standard deviation : ", np.std(array))
print("Variance : ", np.var(array))
print("Minimum Value : ", np.min(array))
print("Max Value : ", np.max(array))
print("Position of Minimum Value : ", np.argmin(array))
print("Position of Max Value : ", np.argmax(array))





Array :  [ 1  2  3  4  5  6  7  8  9 10]

Sum :  55
Average :  5.5
Mean :  5.5
Standard deviation :  2.8722813232690143
Variance :  8.25
Minimum Value :  1
Max Value :  10
Position of Minimum Value :  0
Position of Max Value :  9


In [2]:
import numpy as np

array = np.arange(20).reshape(4,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
for i in np.nditer(array, order="K"):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

Masking : numpy.ma

In [ ]:
import numpy.ma as ma

arr = np.array([*range(15)])

print(arr)
print(ma.masked_equal(arr, value=10))           # will mask all values equal to 10 in the array
print(ma.masked_greater_equal(arr, value=10))   # will mask all values greater & equal to 10 in the array

print(ma.masked_inside(arr, 5, 11))             # masks values between a specified range (5 till 11)
print(ma.masked_outside(arr, 5, 11))            # masks values outside a specified range (5 till 11)


print(ma.masked_where(arr % 2 == 0, arr))       # mask all the even numbers in array

print("\n")
arr_inv = [1,2,3,4,np.inf,6,7,np.nan,9]
print(arr_inv)
print(ma.masked_invalid(arr_inv))               # masks invalid values like nan, infinity, etc


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9 -- 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9 -- -- -- -- --]
[0 1 2 3 4 -- -- -- -- -- -- -- 12 13 14]
[-- -- -- -- -- 5 6 7 8 9 10 11 -- -- --]
[-- 1 -- 3 -- 5 -- 7 -- 9 -- 11 -- 13 --]


[1, 2, 3, 4, inf, 6, 7, nan, 9]
[1.0 2.0 3.0 4.0 -- 6.0 7.0 -- 9.0]


In [15]:
## Vectorization example

array = np.array([*range(20)])
print(array)

def cube_if_even(num):
    """
    Returns cube of number if its is Even, else returns same number
    """
    if num%2 == 0:
        return num ** 3
    else:
        return num


vectorized_cube_if_even = np.vectorize(cube_if_even)

print(vectorized_cube_if_even(array))

    



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[   0    1    8    3   64    5  216    7  512    9 1000   11 1728   13
 2744   15 4096   17 5832   19]


In [ ]:
# defining custom data type

dt = np.dtype("i4")

arr1 = np.array(["1111","2222","3333"])
print(arr1, arr1.nbytes)

arr2 = np.array(["1111","2222","3333"], dtype=dt)      # specify the datatype as Int with length 4 bytes
print(arr2, arr2.nbytes)         # notice the change in datatype and total bytes                       


['1111' '2222' '3333'] 48
[1111 2222 3333] 12
